name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y cmake build-essential
    
    - name: Configure CMake
      run: cmake -B build
      
    - name: Build
      run: cmake --build build

    - name: Test binary
      run: |
        cd build
        if [ -f "ATmega328Compiler" ]; then
          echo "Binary successfully created"
          ./ATmega328Compiler --version
        else
          echo "Binary not found"
          exit 1
        fi

    - name: Run tests
      run: |
        cd build
        ctest --output-on-failure