name: Create Release

on:
  push:
    tags:
      - 'v*.*.*'  # Triggers on tags like v1.0.0, v2.1.3, etc.
  workflow_dispatch:  # Allows manual triggering from the GitHub UI

permissions:
  contents: write
  releases: write

jobs:
  build-and-release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y cmake build-essential

      - name: Configure CMake
        run: cmake -B build

      - name: Build Project
        run: cmake --build build --config Release

      - name: Verify Binary
        run: |
          cd build
          if [ -f "ATmega328Compiler" ]; then
            echo "Binary successfully created"
            chmod +x ATmega328Compiler
          else
            echo "Binary not found"
            exit 1
          fi

      - name: Create GitHub Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref_name }}
          release_name: Release ${{ github.ref_name }}
          body: |
            ### Changes
            - Describe the changes or refer to commit history.
          draft: false
          prerelease: false

      - name: Upload Release Binary
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./build/ATmega328Compiler
          asset_name: ATmega328Compiler_${{ github.ref_name }}_linux
          asset_content_type: application/octet-stream

      - name: Upload HEX File
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./build/examples/minimal_led_test.hex
          asset_name: minimal_led_test_${{ github.ref_name }}.hex
          asset_content_type: application/octet-stream

      - name: Upload BIN File
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./build/examples/minimal_led_test.bin
          asset_name: minimal_led_test_${{ github.ref_name }}.bin
          asset_content_type: application/octet-stream